on:
  push:

jobs:
  build-svc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: pmorelli92/github-container-registry-build-push@1.0.1
        name: Build and Publish latest service image
        with:
          # Read note below to see how to generate the PAT
          personal-access-token: ${{secrets.GHCR_PAT}}
          docker-image-name: kali
          docker-image-tag: latest
          dockerfile-path: ./Dockerfile
          build-context: .
